apiVersion: v1
kind: Secret
metadata:
  # Используем имя релиза Helm, чтобы манифесты не конфликтовали
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Магия Helm: он сам переведет текст из values в Base64 "на лету" при деплое
  APP_PASSWORD: {{ .Values.auth.password | b64enc }}
