apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: pushgateway
  endpoints:
  - port: app-metrics
    path: /metrics
    interval: 10s
